version: 1
services:
  - type: web
    name: ai-blog-generator
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ai_blog_app.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ai_blog_app.settings
