# services:
#   - type: web
#     name: ai-blog-backend
#     runtime: python
#     pythonVersion: 3.10.13
#     buildCommand: "pip install -r requirements.txt"
#     startCommand: "gunicorn ai_blog_app.wsgi:application"
#     envVars:
#       - key: DJANGO_SETTINGS_MODULE
#         value: ai_blog_app.settings
#       - key: PORT
#         value: 8000

services:
  - type: web
    name: ai-blog-app
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn ai_blog_app.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ai-blog-db # You can change this name if you want
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: ASSEMBLYAI_API_KEY
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false

databases:
  - name: ai-blog-db # This name must match the one under fromDatabase
    plan: free
