services:
  - type: web
    name: ai-blog-backend
    runtime: python
    pythonVersion: 3.10.13
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn ai_blog_app.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ai_blog_app.settings
      - key: PORT
        value: 8000
