# """
# Django settings for ai_blog_app project.

# Generated by 'django-admin startproject' using Django 5.0.4.

# For more information on this file, see
# https://docs.djangoproject.com/en/5.0/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.0/ref/settings/
# """
# import dj_database_url
# from pathlib import Path
# import os
# from dotenv import load_dotenv


# # DATABASES = {
# #     'default': dj_database_url.config(conn_max_age=600, ssl_require=True)
# # }

# DATABASES = {
#     'default': dj_database_url.config(
#         # Feel free to set a default for local development.
#         default='sqlite:///' + os.path.join(BASE_DIR, 'db.sqlite3'),
#         conn_max_age=600
#     )
# }

# # Load environment variables from .env file
# load_dotenv()

# # Now you can access the DATABASE_URL variable
# # DATABASE_URL = os.getenv('DATABASE_URL')



# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent

# # Add the following in your settings.py

# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# # SECRET_KEY = 'django-insecure-l%7$kbob@-is+=rlid-zg#l#ijf64j1dhzyfw1s!%r77r%py&7'
# SECRET_KEY = os.environ.get('SECRET_KEY')

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False

# # YOUTUBE_COOKIES_FILE = os.path.join(BASE_DIR, 'cookies.txt') if DEBUG else 'etc/secrets/cookies.txt'

# YOUTUBE_COOKIES_FILE = os.getenv('YOUTUBE_COOKIES')

# YOUTUBE_API_KEY = os.getenv('YOUTUBE_API_KEY')

# # ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'ai-blog-app-afz1.onrender.com' ]

# ALLOWED_HOSTS = []

# RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
# if RENDER_EXTERNAL_HOSTNAME:
#     ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# PORT = os.environ.get('PORT', '8000')

# # Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'blog_generator'
# ]

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
#     'whitenoise.middleware.WhiteNoiseMiddleware',
# ]

# # ROOT_URLCONF = 'Backend.urls'
# ROOT_URLCONF = 'ai_blog_app.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [BASE_DIR, 'templates'],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# # WSGI_APPLICATION = 'Backend.wsgi.application'
# WSGI_APPLICATION = 'ai_blog_app.wsgi.application'


# # Database
# # https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.sqlite3',
# #         'NAME': BASE_DIR / 'db.sqlite3',
# #     }
# # }

# # DATABASES = { 'default':dj_database_url.config(default=DATABASE_URL)}

# # Database configuration for local PostgreSQL

# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.postgresql',
# #         'NAME': 'postgres',  # Replace with the name of your local DB
# #         'USER': 'postgres',  # Replace with your local PostgreSQL username (usually 'postgres')
# #         'PASSWORD': 'mak@123',  # Replace with your local password
# #         'HOST': 'localhost',  # Host is localhost for local PostgreSQL
# #         'PORT': '5432',  # Default port for PostgreSQL
# #     }
# # }



# # Static files settings
# STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# # ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'ai-blog-app-afz1.onrender.com', '*']

# # This line collects static files into STATIC_ROOT directory
# # Run this during deployment




# # Password validation
# # https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/5.0/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.0/howto/static-files/



# # Default primary key field type
# # https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# LOGIN_URL = 'login'



"""
Django settings for ai_blog_app project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file during local development
load_dotenv()

# --- Core Security Settings ---

# SECRET_KEY is loaded from an environment variable. Render will generate this for you.
SECRET_KEY = os.environ.get('SECRET_KEY')

# DEBUG is True for local development, but will be False in production on Render.
# Render sets the 'RENDER' environment variable to 'True'.
DEBUG = os.environ.get('RENDER') != 'True'

# --- Host and Application Configuration ---

# This dynamically adds your Render app's URL to the allowed hosts.
ALLOWED_HOSTS = []
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog_generator'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise Middleware should be placed directly after the security middleware.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ai_blog_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ai_blog_app.wsgi.application'


# --- Database Configuration ---
# This setup uses the DATABASE_URL from Render in production,
# but falls back to a local SQLite database for development.

DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///' + os.path.join(BASE_DIR, 'db.sqlite3'),
        conn_max_age=600
    )
}


# --- Password Validation ---
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# --- Internationalization ---
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# --- Static Files (CSS, JavaScript, Images) ---
# https://docs.djangoproject.com/en/5.0/howto/static-files/
# http://whitenoise.evans.io/en/stable/django.html

STATIC_URL = '/static/'
# This is where Django will collect all static files during the build.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# This setting makes WhiteNoise more efficient at serving files.
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# --- Media Files (User Uploads) ---
# NOTE: This configuration is for local development only. For production, you
# must configure a third-party storage service like AWS S3 or Cloudinary.
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# --- Other Settings ---

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_URL = 'login'

# API Keys loaded from environment variables
YOUTUBE_COOKIES_FILE = os.getenv('YOUTUBE_COOKIES')
YOUTUBE_API_KEY = os.getenv('YOUTUBE_API_KEY')

